In [7]:
import numpy as np
import time
import sys

In [5]:
a = np.array([1,2,3])
b = np.array([(1,2,3), (4,5,6)])

In [6]:
print(a,b)

[1 2 3] [[1 2 3]
 [4 5 6]]


In [8]:
#Advantage of mumpy over list
# 1) Less Memory
# 2) Fast
# 3) Convenient

In [10]:
s = range(1000)

sys.getsizeof(5)*len(s)

28000

In [11]:
d = np.arange(1000)

d.size * d.itemsize

4000

In [28]:
SIZE = 1000000

In [29]:
L1 = range(SIZE)
L2 = range(SIZE)

start = time.time()

result = [x+y for x,y in zip(L1,L2)]

print((time.time() - start) * 1000)

107.7122688293457


In [30]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()

result = A1 + A2

print((time.time() - start) * 1000)

26.91507339477539


In [36]:
a = np.array([[1,2,3], [4,5,6]])
a = np.array([1,2,3])
a.ndim

1

In [37]:
a.itemsize

4

In [38]:
a.dtype

dtype('int32')

In [39]:
a = np.array([1,2,3])
a.size

3

In [40]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [42]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [47]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0,3])
print(a[0:,3])
print(a[0:2,3])

4
[ 4  8 12]
[4 8]


In [51]:
a = np.linspace(1,3,5)
print(a)
a = np.linspace(1,3,10)
print(a)

[1.  1.5 2.  2.5 3. ]
[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [52]:
a = np.array([1,2,3,4])
print(a.min())
print(a.max())
print(a.sum())

1
4
10


In [53]:
a = np.array([[1,2,3],[4,5,6]])

print(a.max(axis=0)) #column wise
print(a.max(axis=1)) #row wise

[4 5 6]
[3 6]


In [55]:
a = np.array([[1,2,3],[4,5,6]])
print(np.sqrt(a))
print(np.std(a))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933


In [56]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [58]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [59]:
a = np.array([[1,2,3],[4,5,6]])

np.ravel(a)

array([1, 2, 3, 4, 5, 6])